// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCij5MVhz4p2FLcxQy5cSMO1j7XW8q1sZ4',
    appId: '1:748589664990:web:5ebf89b6915a0c0f20904f',
    messagingSenderId: '748589664990',
    projectId: 'messenger-gsc',
    authDomain: 'messenger-gsc.firebaseapp.com',
    storageBucket: 'messenger-gsc.appspot.com',
    measurementId: 'G-V1S1BSKTE0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDITY90kmV7GZLE7InD_s9L5SJgUTWBrZI',
    appId: '1:748589664990:android:be492ee794e4de7a20904f',
    messagingSenderId: '748589664990',
    projectId: 'messenger-gsc',
    storageBucket: 'messenger-gsc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSv0q7voxkNElALY7F3Jcg4Wg8L9b6b-w',
    appId: '1:748589664990:ios:e4efaedda599277c20904f',
    messagingSenderId: '748589664990',
    projectId: 'messenger-gsc',
    storageBucket: 'messenger-gsc.appspot.com',
    iosBundleId: 'com.example.messenger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSv0q7voxkNElALY7F3Jcg4Wg8L9b6b-w',
    appId: '1:748589664990:ios:3101ad6f64e3a71120904f',
    messagingSenderId: '748589664990',
    projectId: 'messenger-gsc',
    storageBucket: 'messenger-gsc.appspot.com',
    iosBundleId: 'com.example.messenger.RunnerTests',
  );
}
